[BE] 회원가입 중복 확인 로그인 개인정보 조회
codesquad-member-2020/signup-5 pull request #62
Opened 2020-03-27 08:05 UTC by moonelysian

아마 #58 만 보시면 되지않을까 합니당..? 아마..메이비...ㅜ

- 회원가입, 개인정보조회
    UserController

- 중복확인
    - DuplicateController

- 로그인
    - AuthController

### API 정리 문서
https://documenter.getpostman.com/view/3004320/SzS8sk7n?version=latest

2020-03-29 06:56 UTC, wheejuni requested changes
수고 많으셨습니다.
코멘트 드린 내용 참고해주세요.

2020-03-29 06:56 UTC, wheejuni commented on .gitignore
> +<<<<<<< HEAD
파일에 conflict mark가 그대로 묻어있네요....

2020-03-29 06:56 UTC, wheejuni commented on BE/signup/src/main/java/com/codesquad/signup/controller/AuthController.java
> +    static final String PASSWORD = "password";
`private` 붙여주세요.

2020-03-29 06:56 UTC, wheejuni commented on BE/signup/src/main/java/com/codesquad/signup/controller/DuplicateController.java
> +    public Object isDuplicate(String userId, String email, String phone) {
리턴타입으로 Object를 쓰는 건 자제해주세요.

2020-03-29 06:56 UTC, wheejuni commented on BE/signup/src/main/java/com/codesquad/signup/controller/DuplicateController.java
> +        Optional<User> user = userRepository.findByPhoneNumber(phone);
단순히 전화번호 중복체크를 위해서 유저 전체를 받아오는 건 좋지 않아보이고요, 
`COUNT` 쿼리 등을 사용하는 것으로 개선해보면 어떨까 생각이 드네요.

2020-03-29 06:56 UTC, wheejuni commented on BE/signup/src/main/java/com/codesquad/signup/controller/DuplicateController.java
> +        if (user.isPresent())
조건문에 중괄호 `{` 잊지 말아주세요.

2020-03-29 06:56 UTC, wheejuni commented on BE/signup/src/main/java/com/codesquad/signup/exception/CustomAdvice.java
> +    @ResponseStatus(HttpStatus.CONFLICT)
`CONFLICT` 는 흔하게 쓰지 않는 상태코드이긴 합니다만, 클라이언트 사이드와 협의가 잘 되었다면, 크게 상관은 없겠네요.

2020-03-29 06:56 UTC, wheejuni commented on BE/signup/src/main/java/com/codesquad/signup/repository/User.java
> +  public void checkValidUser() {
https://webcoding.tistory.com/entry/Spring-JSR-303-%EC%9C%BC%EB%A1%9C-%EA%B0%9D%EC%B2%B4-%EA%B0%92-%EA%B2%80%EC%A6%9D%ED%95%98%EA%B8%B0 참고하셔서 JSR-303 규격에 대해 한번 학습해보시고 다음부턴 적용해보세요.

2020-03-29 06:56 UTC, wheejuni commented on BE/signup/src/main/java/com/codesquad/signup/repository/User.java
> +      log.debug("### ERROR : isCorrectUserIdFormat");
그리고 유저의 입력에 따라 좌우되는 값에 대해서 ERROR 라고 로깅하는 것은 좀 어색해 보입니다.

2020-03-29 06:56 UTC, wheejuni commented on BE/signup/src/main/java/com/codesquad/signup/util/VerifyFormatUtil.java
> +        if (interest == null) return false;
if문 블록이 한 줄이어도 꼭 중괄호 열어주시고, 줄바꿈 해주세요.

2020-04-07 05:53 UTC, honux77 commented on BE/signup/src/main/java/com/codesquad/signup/controller/DuplicateController.java
> +        Optional<User> user = userRepository.findByPhoneNumber(phone);
https://codingexplained.com/coding/java/spring-framework/return-boolean-value-from-spring-data-jpa-query

2020-04-07 06:16 UTC, honux77 commented
수고하셨어요!

2020-04-07 06:16 UTC, closed without merging